### PR TITLE
chore: 2021 Dec update

### PR DESCRIPTION
**Pull request by jrconlin**
* includes latest clippy fixes

### CODE REVIEW

**Comment by tiesselune** [comment]
@jrconlin Sorry for the delay, I'll check this ASAP

**Review by tiesselune — APPROVED** [review]
This PR only changes crate version, enum variant case, and references. 
Compiling and passing tests ensures no errors have been introduced.

**Review by tiesselune — APPROVED** [review]

**Review by lougeniaC64 — APPROVED** [review]
@jrconlin LGTM (albeit with noob eyes)

**Comment by jrconlin** [comment]
Holding off pushing a new release until Monday

**Pull request merged**
